version: '3.3'
services:
  app:
    build: .
    ports:
      - 8081:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bcMongo
    volumes:
      - .:/src      
    
  mongo:
    image: mongo
    container_name: mongodbPrueba
    restart: always
    ports:
      - 2208:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: